language: node_js

node_js:
  - '0.12'

before_install: npm install -g grunt-cli

script: 'grunt jshint && npm run test-node && npm run test-browser-travis'

env:
  global:
    - secure: rx4B+ydN0SH4yMSif/eiZ7+lBmG0ErihvNCz0NIiZwNbgL/VCslY7BwIlJB2f0MQOUCqHb/GdkS5ozEVs6sUMbOiAAQaN3wHJWxOCaA9aJVNHnYC/528petaRbMCBy2sef8T5nRULFDOKEKw7nAaRTsgJOSQZWg/JdHDQH9LnF2z2/+uoByvyNb+SUtoMHzKbxPJM9/WuWJOqDrcjMZKVTqDCJrWGfj9Wst6+bNQMrRDgbkQ557tHqliDVopyr6UP5KHuQlsbElAEE3IFVOIELo7FkVD/rvIbr3e8wCoeFKgibEF/u5DjQfeJ5Z7yBCQz36ZTe1d5DOSfKPzQ00GlZ34evx2r3dOb4Ckvz6btdBkOH/T3dTD/Ju5I60nAIucK76S20/t+guNbuQBf3ZL00jHlet7XKDX3C8582Jw5TGLnopOwma0dKdwEBMyDZUmT57zR5uw/Q+P2cdkLdCzDAd5X8lp+L/81kx2IpIN9l2k0PQfBjG8Piv4DQN2ZAF4dXjiXrwXvC3W2fk8XNkhGIBXyruAdYAoF9EFZotU7K33LU6pA5Kvr02dMh+6NGeOXIstRs/FkAnuHuIthPGCf6yk6fckDDKgAnTOUgPgM2Z6j++d+qbpUAlkIkzB67M5xNGDBvlO7Ms7PVqGgAOubPfyF/Yz58XvL6KGBv6U7ug=
    - secure: XCjULYiKMcmzTX1nOLtm4sFB6A+ysuCSIA68EnlLt8uObk/UA5SlbwTNcNflNk7qLqZFkrWhiXk18Najf5+rYtRf3GooRq1TA/EtKWtLJCF9ErjgCe8Xmzy2qEn2bRarBjLKDGL3srDdimwZJDDFRv5b6md/ZC1agfVik4rEJvtc7b8w3l0vW1qSc/Fk1uHxWxRd4ToMxMD+IMyK6QlvXkNtJt9wj8WSQhVsa9PkX0fXoCTnYBiH8M7QxoIe7R5vzpe3K1BiMT/SitjwED6dvNoHJXC70u/gzrSHXgvD1yCIeadfH/RJQhmWykG+HwzH8x8cex2g58iwoo7yrcWzIUZB5cSOpmWNb06o7BPktJlLm1Kp0Fidi9avnCvnPQh1ID+Gvb9cNllrgW0WB3H6WwhpaCDIqVmorOiSz3DVWOXFg7F72DYXvFMV5eFbSVsUAIM76YeabjdbITfEZauhogFvEYjkTinTgxatvDGqlXD6OwkbbStElbaVDSl8ayjGxvvcVguAO7YtXoBwt/Xuzqj8uJYx0WSwC45HXVMxBrm1GITIREY9/xv0/F+ek9uBy1fwuXwCuV8PQmiyVKtuLjh/dlNnimc+43y89CHTwoso9Tykvb4Mw6l/2OxZY/6su++4mV1/c826Nr/dwpi1DS2QTEwTO1yRlbAxuqtqbYc=
